### ISSUE TITLE
Swagger spec validation errors

### ISSUE THREAD

**Issue by sabedevops** [openziti/fabric#535]
![image](https://user-images.githubusercontent.com/22971615/201163037-74a6b3de-77a7-425b-b08d-300ed5c5531e.png)

The swagger specification lacks a `securityDefinitions` section that causes errors during spec validation. It seems the same definitions used in the edge apis can be used here:

```yaml
securityDefinitions:
  ztSession:
    description: An API Key that is provided post authentication
    type: apiKey
    name: zt-session
    in: header
```

Additionally, the `type` of `#/definitions/inspectResponseValue.properties.value` is currently a list, but per the OAS2 spec, this is invalid and should  instead be a string representing a single type.
